name: Build and Push Docker Image

on:
  push:
    branches:
      - master 
  workflow_dispatch: # allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/tax-calculator:latest
            ${{ secrets.DOCKER_USERNAME }}/tax-calculator:${{ github.sha }}
